site_name: Tianyi Wiki
nav:
  - 首页: Index.md
  - 关于: About.md
  - 联系: Contact_us.md
  - 天一中学AP课程班: Introduction.md
  - AP的特色组织和活动: Special_Organizations_and_Activities.md
  - 食堂: Cafeteria.md
  - 实用链接: Practical_Links.md
  
# mkdocs.yml
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mouse-firework@latest/dist/index.umd.js  # 库CDN，源代码见 https://github.com/D-Sketon/mouse-firework
  - js/fireworks.js  # 你的配置脚本



theme:
  name: "material"
  palette:
        # 切换到亮色
        - media: "(prefers-color-scheme: light)" # 根据系统的颜色模式自动切换
          scheme: default
          primary: light blue
          accent: light blue
          toggle:
              icon: material/weather-night
              name: 切换到暗色模式

        # 切换到暗色
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: light blue
          accent: light blue
          toggle:
              icon: material/weather-sunny
              name: 切换到亮色模式
              
  custom_dir: docs/CC_BY-NC-SA  # 指向自定义模板目录

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
plugins:
  - glightbox:



  # 此配置允许在代码块和内联代码块上高亮显示语法
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences



extra_css:
  - ../css/cc.css
